### ISSUE TITLE
Source codes of x-y cut, docstrum, Voronoi, Constrained text-line detection, etc are missing.

### ISSUE THREAD

**Issue by IceFlameWorm** [BobLd/DocumentLayoutAnalysis#1]
Hi, the links in the readme to the source codes listed in the title are not available. Can you please check and correct them? Thank you.

**Comment by BobLd** [comment]
Hi,

I have updated the links to the implementations. They are available in [UglyToad.PdfPig.DocumentLayoutAnalysis](https://github.com/UglyToad/PdfPig/tree/master/src/UglyToad.PdfPig.DocumentLayoutAnalysis). Also, have a look at its [wiki](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis) for more info.

**NB**: The implementation of the `Constrained text-line detection` is not finished, I only worked on the `Whitespace Covering algo`. No implementation for the `Voronoi` at the moment.

**Comment by IceFlameWorm** [comment]
Hi, thanks a lot.

**Comment by BobLd** [comment]
no problem
